source ~/.zsh/autojump
source ~/.zsh/bindings
source ~/.zsh/cassandra
source ~/.zsh/clojure
source ~/.zsh/echonest
source ~/.zsh/git
source ~/.zsh/google-cloud-sdk
source ~/.zsh/haskell
source ~/.zsh/heroku
source ~/.zsh/history
source ~/.zsh/java
source ~/.zsh/mcmire.zsh-theme
source ~/.zsh/nvm
source ~/.zsh/npm
source ~/.zsh/python
source ~/.zsh/rails
source ~/.zsh/tmux
source ~/.zsh/unicode
source ~/.zsh/vim
source ~/.zsh/zmv
source ~/.zsh/zzz_aliases
source ~/.zsh/zzz_functions

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH=$PATH:/usr/local/go/bin
export PATH="/usr/local/opt/openjdk/bin:$PATH"
export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin"
